create table restaurant_tables (
    id bigint generated by default as identity primary key,
    table_number varchar(20) not null unique,
    capacity integer not null,
    x_position integer not null,
    y_position integer not null,
    shape varchar(30) not null default 'ROUND',
    active boolean not null default true,
    constraint chk_restaurant_tables_capacity
        check (capacity > 0)
);

create table table_features (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null
);

create table restaurant_table_features (
    restaurant_table_id bigint not null,
    table_feature_id bigint not null,
    primary key (restaurant_table_id, table_feature_id),
    constraint fk_restaurant_table_features_table
        foreign key (restaurant_table_id) references restaurant_tables(id) on delete cascade,
    constraint fk_restaurant_table_features_feature
        foreign key (table_feature_id) references table_features(id) on delete cascade
);

create table reservations (
    id bigint generated by default as identity primary key,
    restaurant_table_id bigint not null,
    customer_name varchar(150) not null,
    customer_email varchar(255) not null,
    party_size integer not null,
    start_time timestamp not null,
    end_time timestamp not null,
    status varchar(30) not null default 'CONFIRMED',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_reservations_table
        foreign key (restaurant_table_id) references restaurant_tables(id),
    constraint chk_reservations_party_size
        check (party_size > 0),
    constraint chk_reservations_time_range
        check (end_time > start_time)
);

create index idx_reservations_table_id on reservations(restaurant_table_id);
create index idx_reservations_start_time on reservations(start_time);
create index idx_reservations_end_time on reservations(end_time);
create index idx_reservations_status on reservations(status);
